### ISSUE TITLE
Nieuwe repo HAN.nl

### ISSUE THREAD

**Issue by Aratramba** [HogeschoolvanArnhemenNijmegen/HAN.nl-pilot#42]
@jennydebever @IVARBureau kan één van jullie een nieuwe, __schone__ repository HAN.nl aanmaken (helemaal leeg dus) ? Dan kan ik die gaan vullen met een opgeschoonde versie van deze pilot repository. Graag dezelfde mensen dezelfde rechten geven.

**Comment by jennydebever** [comment]
@Aratramba staat klaar!

**Comment by jennydebever** [comment]
Laurens ook toegevoegd

**Comment by Aratramba** [comment]
geen hoofdletters dit keer?

**Comment by jennydebever** [comment]
Nieuw jaar, nieuwe inzichten...



Jenny de Bever | Webdeveloper | HAN ICT/SND Webbeheer | Ruitenberglaan 26 Arnhem | Kapittelweg 33  Nijmegen, kamer B0.05 |  T (06) 46 44 73 22 | jenny.debever@han.nl | www.han.nl



Werkdagen: maandag (Arnhem), dinsdag (Nijmegen), woensdag tot 14 uur (Nijmegen), donderdag (Arnhem), vrijdag tot 14 uur (Nijmegen)

Dringende vragen tijdens mijn afwezigheid: webbeheer@han.nl<mailto:webbeheer@han.nl>
________________________________
Van: Arjen <notifications@github.com>
Verzonden: maandag 7 januari 2019 13:46:40
Aan: HogeschoolvanArnhemenNijmegen/HAN.nl-pilot
CC: Bever Jenny de; State change
Onderwerp: Re: [HogeschoolvanArnhemenNijmegen/HAN.nl-pilot] Nieuwe repo HAN.nl (#42)


geen hoofdletters dit keer?

**Comment by jennydebever** [comment]
Toch mooier met hoofdletters, niets zo veranderlijk....
